# See config.example.yml for documentation.
object_base: orig/G9RE7D
object: sys/main.dol
hash: 2156f6152170740733706877fd4ae1d2cff48608
symbols: config/G9RE7D/symbols.txt
splits: config/G9RE7D/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
